cloud:
  aws:
    credentials:
      access-key: AKIAUG4KBC2GH22MHH24
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: fileuploaddownload01


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

